{{- if and .Values.global.kafka.sasl.username .Values.global.kafka.sasl.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "videogenie.fullname" . }}-kafka-creds
  labels:
    {{- include "videogenie.labels" . | nindent 4 }}
type: Opaque
data:
  # Used by application pods
  sasl_username: {{ .Values.global.kafka.sasl.username | b64enc | quote }}
  sasl_password: {{ .Values.global.kafka.sasl.password | b64enc | quote }}
---
# KEDA TriggerAuthentication requires a specific format
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "videogenie.fullname" . }}-keda-kafka-trigger
  labels:
    {{- include "videogenie.labels" . | nindent 4 }}
spec:
  secretTargetRef:
    - parameter: sasl
      name: {{ include "videogenie.fullname" . }}-kafka-creds
      key: sasl_username # Maps to 'username' field in KEDA Kafka trigger
    - parameter: password
      name: {{ include "videogenie.fullname" . }}-kafka-creds
      key: sasl_password # Maps to 'password' field in KEDA Kafka trigger
{{- end }}
