apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  namespace: cicd
spec:
  triggers:
    - name: on-push-main
      bindings:
        - ref: github-push
      template:
        ref: build-deploy-run
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push
  namespace: cicd
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: build-deploy-run
  namespace: cicd
spec:
  params:
    - name: gitrevision
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: build-deploy-
      spec:
        pipelineRef:
          name: build-and-deploy
        params:
          - name: image-tag
            value: $(tt.params.gitrevision)
        workspaces:
          - name: source
            persistentVolumeClaim: { claimName: cicd-source-pvc }
